name: CI

on: [push, pull_request]

jobs:
  generate-reports:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y -qq make sqlite3 wget
    - name: make reports
      run: make 
